language: node_js
script: npm run test-coverage

services:
  - docker
cache:
  apt: true
  directories:
    - node_modules
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  # Docker Config
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASS"
  - export REPO=gravebot/gravebot
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
node_js:
  # - "stable"
  - "4.2"
env:
  global:
    - secure: "gtHun0+ng9v5PrLej9rqtY8jB/Miz6Iofxjn3/pf1AR+Hikpp9rxwwtm4KnXh9sbX66iB3MIIP/btBqo4P5IJm/BekNYdSfZQTnC1pz805ksJq+0Y/ELJ+AehPCRcVwD5WHpCDbONb1lkc3TPkS4KFYLWK2v6/sORM+DT6H7Fnx3UKKeggsyBqwC60+QAJ6QUnNW03wm8HYsFJt01zxp4bymrMle3r+h/SQ3GuIFK/aYrdHKmzUCNYb9oQeaRW+vozDMwDkHmhM/TwkRnP7mCBzGDDTkbizwrnMKLxGPTM8J4nCA1ee73wlDCaPlUWtWU/AOPNggkeCoJgzI2Pp+1VW2nnqQgxszb3EILD4LkJpb+aTsjVUAp688uzDLNcdSCKzz/+B4QpfgZHgOl1qeWBQw+JY0fFSBlNrcOaajC0bvQwvY94H5i3A8VVsh0R192gT7OrIUG+m9xkSHaI0CGuOL3YCJh9lkIz7H3g9CE0Nf0LNjy5dm5U1KjpDj46ketgTuAsSFnpK11dbxJOVmraHE+z3e7EdciuJk+03D0SNUnJI9SrfB8gD39iFv+aI1VTk5KFE7Py3kIUXEldKxE+QqKMk0MijJ7WJKVM45GV6jZe2UBNWslR5o4aysiZzh6TQbk713DbWhTbRmH41jX3n2dnPNql0xFZIgvZ/RnmE="
    - secure: "Fw8L8yP8UnDU1useHacBoTHIp9NW0Xl21P9sdM8SJs7eu+voif6TkuGwb8AuzFMgztKaIK0dtgKSJxf70G84dFJXp3lpyzO0P7IVtWX6BnzQvGYeM1NPvNXw6TV4xMnmFVRz7IaN+xQZNasRle70oLL+ERymyji1KYclKTuZVJrcje6ORETXNFXtsDD0E9o7TrJjz+Pj0TcM+vT6otxSjCRWRGOtJgl51bA/OEeqjQ5Ptf6ySHjkWxkqzZ9EdRh2zb1vhMii+6Nfzkje6CNjfJk12uhqwVzQ0P2imYfDFlLM8/d/pDLJsXl9YVnY5VXCeaDwZdTCi1AJnitbUBjEMtDTEKc5qag62PqLGvTIHx3sXLCE4e8fjIq+1h+xtElhTt8cQjWwE+5jGFfr9u4rAaTtvlJ/Rg3H+Tk9axWrGpEPqiq+uXADoxz/R1UNHFFn98KSk3wiwg/1tlU8hsLUld79xP+d4uVxD/oncPeRGKeTsvDaCBYO3i0Yk7FbuyT7V2tKv9wHC09K/g2zNa0dXYKQQeMuN/vffj8Z78hkGy0Lg67wXtLGclrV7idI/5WqpUvQSubBF8J7sBPUY6Q4Jl3/b29a3vftlkFNsGC+DOYbvi1Y1gRN1ZNdztC+4xEBNPUYqtXaP4CDBVcQGMzhkPUlBqpSwtETvQv1MPuLY+Q="
    - secure: "jbbXAQtMX+35fBY9Um88zZWeGWlpyDaoh/nDaqsgdfryu+irmNgH5PIvzevKX21qgKiS2TVLzVfdxPrOnjCMdUgwva/B3wUAHnLiXlUCJE8UPZZqVjg98EnkoKrhUyPvHjusxT9PSCXgLR8YBKE+ZIkzq6KjUR1bUwScRqmFEiqrj+h8/ZaXansvKj5dRmKbC9nFHwQ9OrzmQShBOsws3wYnV2VfmGOckSp8fgjWzzZ1vrqM/ACRcP7TSJ8jMH3e/NdK9qLe70WpKKAp8lqwt0JvN4pntkYvscOH+v7x344ckF9k+vcIPRZ5pvp7Odz6jvc+u4AkwHL0rMLbrvAgEGVB/G62JdHV6cixew0xcfrK8tyK3IoyyAjiSqd0ACNCgsPZmSCMnLRUEvpA6ZXlt0UWS1G+eSWzYsYNW2IsFWy6BUiqwipj+pEKmHlnkXVIy2hCtMzZQd0jbt1rXzlctyQvNUjcUbPVujwe7iRDddWaBOcRkc4yDjQmFU9g6YJ5VZsrxUKv2+MMxVsNUv5AMKFY0mTJT6V7mrRPnmY6zs9Cm4yC8OKxUlx7XRVpL4TwtweX+R6ZS9xjZJtFbZrYn48SHe8JzJHt/DqU8CmL2cF+SrB9s3eYhEK+p9M1ilHy1HsrOiLwHAKAJjJ54KuBtQb/vEXFYkeyfvh2wLeyHUk="
    - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libxml2-dev

deploy:
  provider: heroku
  app: gravebot
  api_key:
    secure: s6aTez2uch+UTC0e553wUtEh2g71aLlJuuq72OwtgRh5RAplRqBmD+vAcah80uJ8tjFGTe2fSSVZuvGXKFY+D1bGlBDeflNgNnaaxYOIbc8KxqSEYg5OWaR6vVNBgfoAlSVbUgBmMuY2VvC4Csd4e/hr7CN7oecbPzG+64JD5WuipSkLzSZvnt5PTnoJzVm0BVrZengYnK41DyCnKCLo5eXq2E4N52f6V9RbUft9GRnqFu1NNGcquapP/gPja/NDhr2TnIoDv7aQVIzJJ85FMRxDIYYbq+XNR+qk/RVXQA7Q1Kss+aSa7jYnHGC23LJX9dlkd9jOeTxgkNeIuUSRK8jMYDFYIs7ofGHd8BV4eWgKKHimMJ0qW21LgI6m/dgnqhaod6jB2uwF5jgbMX6CxjfkIH0QUXhMadzaTdeGyH2MCT8zz+6kRimqD3h/BVHuXJhP2FuhDxIbrLtgSTwBg2yEFDJZGU0QZXLHTTVyIHViCBi6azCWz2Vo5HdplUKAibky1HxqUOOgjCtAPl/XzG4FFJlKJiceHXE7DoqS22V6tLpTPzBwfxYe1phzJQ4+ia+9IA+pqwOPqEnjJAyhb41+TcrjKSuwR7C4ayLJ6gqBKd0Lywbkjwq6vf1Y66mR8qlebfUmxaV8UhKDZaCIzXUcJ3k+NYWLsYOIF+nvaqc=
