language: node_js
script: npm run test-coverage
cache:
  directories:
    - node_modules
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
node_js:
  - "stable"
  - "4.2"
