version: '{branch}-{build}'
pull_requests:
  do_not_increment_build_number: false
skip_tags: true
os: Windows Server 2012 R2
install:
  - systeminfo | findstr /B /C:"OS Name" /C:"OS Version" /C:"System Type"
  - ps: Install-Product node 4.2.3 # Must match package.json
  - npm i -g npm@2.14.7 # Must match package.json
  - npm i
  - node -v
  - npm -v
build: off
platform:
  - x86
  - x64
test_script:
  - npm test
